document.write('			<div class="MenuArea">');
document.write('				<img src="../img/button/slide_left.gif" alt="좌측접기" class="slideLayout"/>');
document.write('				<img src="../img/button/slide_right.gif" alt="좌측열기" class="slideLayout2"/>');
				
document.write('				<h1><img src="../img/menu/h1_1.jpg" alt="" /></h1>');
				
document.write('				<!-- 랭킹존 h1_1, 종목발굴 h1_2, 투자의 달인 h1_3, 투자컨설팅 h1_4, 투자 교육/방송 h1_5, 자자의 하루공감 h1_6 -->');
				
document.write('				<div class="subMenu">');
document.write('					<!-- 랭킹존 Start -->');
document.write('					<ul id="LeftMenu_1">');
document.write('						<li class="sub_rank_1"><a href="/ranking/type_1.html"><span>종목랭킹</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_rank_1_1"><a href="/ranking/type_1.html"><span>실시간 인기종목</span></a></li>');
document.write('								<li class="sub_rank_1_2"><a href="/ranking/type_2.html"><span>보유인기종목</span></a></li>');
document.write('								<li class="sub_rank_1_3"><a href="/ranking/type_3.html"><span>신규 관심종목</span></a></li>');
document.write('								<li class="sub_rank_1_4"><a href="/ranking/type_4_1.html"><span>실시간 매수/매도</span></a></li>');
document.write('								<li class="sub_rank_1_5"><a href="/ranking/type_5_1.html"><span>외국인 매수/매도</span></a></li>');
document.write('								<li class="sub_rank_1_6"><a href="/ranking/type_6_1.html"><span>업종별 No.1</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_rank_2"><a href="/ranking/fund_1.html"><span>펀더멘털 랭킹</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_rank_2_1"><a href="/ranking/fund_1.html"><span>저PER</span></a></li>');
document.write('								<li class="sub_rank_2_2"><a href="/ranking/fund_2.html"><span>저PBR</span></a></li>');
document.write('								<li class="sub_rank_2_3"><a href="/ranking/fund_3.html"><span>고ROE</span></a></li>');
document.write('								<li class="sub_rank_2_4"><a href="/ranking/fund_4.html"><span>배당수익률 상위</span></a></li>');
document.write('								<li class="sub_rank_2_5"><a href="/ranking/fund_5.html"><span>업종평균대비 저PER</span></a></li>');
document.write('								<li class="sub_rank_2_6"><a href="/ranking/fund_6.html"><span>업종평균대비 저PBR</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_rank_3"><a href="/ranking/master_1_1.html"><span>투자의 달인 랭킹</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_rank_3_1"><a href="/ranking/master_1_1.html"><span>수익률 순위</span></a></li>');
document.write('								<li class="sub_rank_3_2"><a href="/ranking/master_2.html"><span>관심달인 순위</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_rank_4"><a href="/ranking/invest_1.html"><span>이모저모 랭킹</span></a></li>');
document.write('					</ul>');
document.write('					<!--// 랭킹존 End -->');
					
document.write('					<!-- 종목발굴 Start -->');
document.write('					<ul id="LeftMenu_2">');
document.write('						<li class="sub_discover_1"><a href="/discover/map_1.html"><span>주식 Map</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_discover_1_1"><a href="/discover/map_1.html"><span>펀더멘털 랭킹</span></a></li>');
document.write('								<li class="sub_discover_1_2"><a href="/discover/map_2_1.html"><span>차트관심주</span></a></li>');
document.write('								<li class="sub_discover_1_3"><a href="/discover/map_3_1.html"><span>수급관심주</span></a></li>');
document.write('								<li class="sub_discover_1_4"><a href="/discover/map_4.html"><span>차트 패턴 검색</span></a></li>');
document.write('								<li class="sub_discover_1_5"><a href="/discover/map_5.html"><span>영웅의 투자가이드</span></a></li>');
//document.write('								<!--li class="sub_discover_1_6"><a href="#"><span>재무지표 조건 검색</span></a></li-->');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_discover_2"><a href="/discover/research_1.html"><span>리서치 추천</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_discover_2_1"><a href="/discover/research_1.html"><span>신규종목 리포트</span></a></li>');
document.write('								<li class="sub_discover_2_2"><a href="/discover/research_2.html"><span>추천 포트폴리오</span></a></li>');
document.write('								<li class="sub_discover_2_3"><a href="/discover/research_3_1.html"><span>계량 포트폴리오</span></a></li>');
document.write('								<li class="sub_discover_2_4"><a href="/discover/research_4.html"><span>리포트 Key Point</span></a></li>');
document.write('								<li class="sub_discover_2_5"><a href="/discover/research_5.html"><span>리포트 매매신호</span></a></li>');
document.write('								<li class="sub_discover_2_6"><a href="/discover/research_6.html"><span>주간리포트 동향</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_discover_3"><a href="/discover/predict_1.html"><span>주가전망예측</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_discover_3_1"><a href="/discover/predict_1.html"><span>서비스안내</span></a></li>');
document.write('								<li class="sub_discover_3_2"><a href="/discover/predict_2.html"><span>주가전망</span></a></li>');
document.write('								<li class="sub_discover_3_3"><a href="/discover/predict_3.html"><span>지수별업종랭킹</span></a></li>');
document.write('								<li class="sub_discover_3_4"><a href="/discover/predict_4.html"><span>지수별종목랭킹</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('					</ul>');
document.write('					<!--// 종목발굴 End -->');
					
document.write('					<!-- 투자의 달인 Start -->');
document.write('					<ul id="LeftMenu_3">');
document.write('						<li class="sub_expert_1"><a href="/expert/profit_1_1.html"><span>수익률 랭킹</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_expert_1_1"><a href="/expert/profit_1_1.html"><span>누적수익률 랭킹</span></a></li>');
document.write('								<li class="sub_expert_1_2"><a href="/expert/profit_2.html"><span>보유종목수익률 랭킹</span></a></li>');
document.write('								<li class="sub_expert_1_3"><a href="/expert/profit_3.html"><span>매도종목수익률 랭킹</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_expert_2"><a href="/expert/follow_1.html"><span>관심달인 랭킹</span></a></li>');
document.write('						<li class="sub_expert_3"><a href="/expert/trade_1_2.html"><span>달인 매매 현황</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_expert_3_1"><a href="/expert/trade_1_2.html"><span>참가자별 매매내역</span></a></li>');
document.write('								<li class="sub_expert_3_2"><a href="/expert/trade_1_1.html"><span>일자별 매매내역</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_expert_4"><a href="/expert/trade_1_4.html"><span>종목 VS 종목</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_expert_4_1"><a href="/expert/trade_1_4.html"><span>보유종목 비교</span></a></li>');
document.write('								<li class="sub_expert_4_2"><a href="/expert/trade_1_3.html"><span>매매내역 비교</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_expert_5"><a href="/expert/rally_1.html"><span>대회안내</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_expert_5_1"><a href="/expert/rally_1.html"><span>대회요강</span></a></li>');
document.write('								<li class="sub_expert_5_2"><a href="/expert/rally_2.html"><span>참가자프로필</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_expert_6"><a href="#"><span>명예의 전당</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_expert_6_1"><a href="#"><span>수상자 History</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_expert_7"><a href="/expert/rec_list.html"><span>투자의 기술</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_expert_7_1"><a href="/expert/rec_list.html"><span>달인의 종목추천</span></a></li>');
document.write('								<li class="sub_expert_7_2"><a href="/expert/knowhow_list.html"><span>달인이 말해주는 주식 노하우</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('					</ul>');
document.write('					<!--// 투자의 달인 End -->');
					
document.write('					<!-- 투자컨설팅 Start -->');
document.write('					<ul id="LeftMenu_4">');
//document.write('						<!--li class="sub_counsel_1"><a href="#"><span>온라인자산관리센터</span></a></li-->');
document.write('						<li class="sub_counsel_2"><a href="/counsel/manager_1.html"><span>My 매니저</span></a></li>');
document.write('						<li class="sub_counsel_3"><a href="/counsel/book_1.html"><span>상담예약</span></a></li>');
document.write('						<li class="sub_counsel_4"><a href="/counsel/dia_list.html"><span>온라인 투자진단</span></a></li>');
document.write('						<li class="sub_counsel_5"><a href="/counsel/solution_1.html"><span>프리미어 솔루션</span></a></li>');
document.write('					</ul>');
document.write('					<!--// 투자컨설팅 End -->');
					
document.write('					<!-- 교육/방송 Start -->');
document.write('					<ul id="LeftMenu_5">');
document.write('						<li class="sub_edu_1"><a href="/edu/research.html"><span>리서치방송</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_edu_1_1"><a href="/edu/research_1.html"><span>아침을여는 사람들</span></a></li>');
document.write('								<li class="sub_edu_1_2"><a href="/edu/research_2.html"><span>수급관심주</span></a></li>');
document.write('								<li class="sub_edu_1_3"><a href="/edu/research_3.html"><span>업종분석</span></a></li>');
document.write('								<li class="sub_edu_1_4"><a href="/edu/research_4.html"><span>종목분석</span></a></li>');
document.write('								<li class="sub_edu_1_5"><a href="/edu/research_5.html"><span>증시전망</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_edu_2"><a href="/edu/cable.html"><span>케이블 증권방송</span></a></li>');
document.write('						<li class="sub_edu_3"><a href="/edu/vod.html"><span>e-study</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_edu_3_1"><a href="/edu/vod_1.html"><span>자산관리 다이어리</span></a></li>');
document.write('								<li class="sub_edu_3_2"><a href="/edu/vod_2.html"><span>경제/환율/금리 가이드</span></a></li>');
document.write('								<li class="sub_edu_3_3"><a href="/edu/vod_3.html"><span>증권투자의 정석</span></a></li>');
document.write('								<li class="sub_edu_3_4"><a href="/edu/vod_4.html"><span>차트 노하우</span></a></li>');
document.write('								<li class="sub_edu_3_5"><a href="/edu/vod_5_1.html"><span>애니메이션 VOD</span></a></li>');
document.write('								<li class="sub_edu_3_6"><a href="/edu/vod_6.html"><span>온라인 서비스 가이드</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_edu_4"><a href="/edu/school.html"><span>기초 투자교실</span></a></li>');
document.write('						<li class="sub_edu_5"><a href="/edu/seminar_1.html"><span>투자교육 세미나</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_edu_5_1"><a href="#"><span>교육 안내/신청</span></a></li>');
document.write('								<li class="sub_edu_5_2"><a href="#"><span>신청 확인/취소</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_edu_6"><a href="/edu/invest_1.html"><span>모의투자</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_edu_6_1"><a href="/edu/invest_1.html"><span>모의투자 안내</span></a></li>');
document.write('								<li class="sub_edu_6_2"><a href="/edu/invest_2.html"><span>모의투자 참가 신청/취소</span></a></li>');
document.write('								<li class="sub_edu_6_3"><a href="/edu/invest_3.html"><span>모의투자 중계</span></a></li>');
document.write('								<li class="sub_edu_6_4"><a href="/edu/invest_4.html"><span>모의투자 게시판</span></a></li>');
document.write('								<li class="sub_edu_6_5"><a href="/edu/invest_5.html"><span>마이계좌</span></a></li>');
//document.write('								<!--li class="sub_edu_6_6"><a href="#"><span>해외선물/FX마진모의투자</span></a></li-->');
document.write('							</ul>');
document.write('						</li>');
document.write('					</ul>');
document.write('					<!--// 교육/방송 End -->');
					
document.write('					<!-- 자자의 하루공감 Start -->');
document.write('					<ul id="LeftMenu_6">');
document.write('						<li class="sub_day_1"><a href="/day/lounge.html"><span>자자의 라운지</span></a></li>');
document.write('						<li class="sub_day_2"><a href="/day/rank_1.html"><span>이모저모 랭킹</span></a>');
//document.write('							<!--ul>');
//document.write('								<li class="sub_day_2_1"><a href="#"><span>수익률 랭킹</span></a></li>');
//document.write('								<li class="sub_day_2_2"><a href="#"><span>배지랭킹</span></a></li>');
//document.write('								<li class="sub_day_2_3"><a href="#"><span>최다 Follower</span></a></li>');
//document.write('								<li class="sub_day_2_4"><a href="#"><span>인기! 포트폴리오</span></a></li>');
//document.write('							</ul-->');
document.write('						</li>');
document.write('						<li class="sub_day_3"><a href="/day/lounge_timeline.html"><span>라운지 타임라인</span></a></li>');
document.write('						<li class="sub_day_4"><a href="/day/hot_list.html"><span>오늘의 핫핏</span></a></li>');
document.write('						<li class="sub_day_5"><a href="/day/s_catch.html"><span>운영자 뉴스피드</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_day_5_1"><a href="/day/s_catch.html"><span>S캐치 트윗</span></a></li>');
document.write('								<li class="sub_day_5_2"><a href="/day/newsletter.html"><span>S캐치 뉴스레터</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('					</ul>');
document.write('					<!--// 자자의 하루공감 End -->');
					
document.write('					<!-- 서비스 안내/가입 Start -->');
document.write('					<ul id="LeftMenu_7">');
document.write('						<li class="sub_join_1"><a href="#"><span>서비스 안내</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_join_1_1"><a href="#"><span>S캐치 서비스 소개</span></a></li>');
document.write('								<li class="sub_join_1_2"><a href="#"><span>S캐치 모델</span></a></li>');
document.write('								<li class="sub_join_1_3"><a href="#"><span>S캐치 이용안내</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_join_2"><a href="/join/step1.html"><span>서비스 가입</span></a></li>');
document.write('						<li class="sub_join_3"><a href="/etc/faq_1.html"><span>FAQ</span></a></li>');
document.write('					</ul>');
document.write('					<!--// 서비스 안내/가입 End -->');
					
document.write('					<!-- 마이페이지 Start -->');
document.write('					<ul id="LeftMenu_8">');
document.write('						<li class="sub_my_1"><a href="/mypage/portfolio_1.html"><span>포트폴리오</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_my_1_1"><a href="/mypage/portfolio_1.html"><span>자자의 포트폴리오</span></a></li>');
document.write('								<li class="sub_my_1_2"><a href="/mypage/portfolio_2.html"><span>실계좌 포트폴리오</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_my_2"><a href="/mypage/counsel.html"><span>상담신청내역</span></a></li>');
document.write('						<li class="sub_my_3"><a href="#"><span>스크랩</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_my_3_1"><a href="/mypage/scrap_1.html"><span>종목 스크랩</span></a></li>');
//document.write('								<!--li class="sub_my_3_2"><a href="#"><span>페이지 스크랩</span></a></li-->');
document.write('								<li class="sub_my_3_3"><a href="/mypage/scrap_3.html"><span>동영상 스크랩</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_my_4"><a href="/mypage/master.html"><span>관심달인</span></a></li>');
document.write('						<li class="sub_my_5"><a href="/mypage/follow_1.html"><span>Following/Follower</span></a></li>');
document.write('						<li class="sub_my_6"><a href="/mypage/badge.html"><span>배지</span></a></li>');
document.write('						<li class="sub_my_7"><a href="/mypage/modify.html"><span>개인정보관리</span></a>');
document.write('							<ul>');
document.write('								<li class="sub_my_7_1"><a href="/mypage/modify.html"><span>나의 정보조회/수정</span></a></li>');
document.write('								<li class="sub_my_7_2"><a href="/mypage/sec.html"><span>서비스 해지 신청</span></a></li>');
document.write('							</ul>');
document.write('						</li>');
document.write('						<li class="sub_my_8"><a href="/mypage/alram.html"><span>시세/지수 알리미</span></a></li>');
document.write('						<li class="sub_my_9"><a href="/mypage/alram_2.html"><span>S캐치 알리미</span></a></li>');
document.write('					</ul>');
document.write('					<!--// 마이페이지 End -->');
document.write('				</div>');
document.write('			</div>');