document.write('<!--[if IE 8]><link rel="stylesheet" type="text/css" href="../css/ie8.css" media="all" /><![endif]-->');

document.write('<!-- Messenger Start -->');
document.write('<div class="TalkBox" style="display:none;">');
document.write('	<!-- Header Start -->');
document.write('	<dl class="Top">');
document.write('		<dt><img src="../img/messenger/title.gif" alt="15자 투자톡톡!" /></dt>');
document.write('		<dd class="help"><a href="#"><img src="../img/messenger/help.gif" alt="15자 투자톡톡이란?" /></a></dd>');
document.write('		<dd class="date">2012.06.30</dd>');
document.write('		<dd class="close"><a href="#"><img src="../img/messenger/btn_close_01.gif" alt="닫기" /></a></dd>');
document.write('	</dl>');
document.write('	<!--// Header End -->');
	
document.write('	<!-- content Start -->');
document.write('	<div class="Middle">');
document.write('		<!-- Start -->');
document.write('		<div class="msgBlock">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl>');
document.write('				<dt><strong>이건나</strong> / 14:21</dt>');
document.write('				<dd class="msg">내가쓴글임내가쓴글임내가쓴글임</dd>');
document.write('				<dd class="btn"><span>');
document.write('					<a href="#"><img src="../img/messenger/btn_write.png" alt="글쓰기" /></a>');
document.write('					<a href="#"><img src="../img/messenger/btn_del.png" alt="삭제" /></a>');
document.write('				</span></dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
			
document.write('			<!-- 댓글 입력 -->');
document.write('			<div class="write" style="display:none;">');
document.write('				<input type="text" value="15자 이내로 작성해 주세요." title="댓글입력" /><a href="#"><img src="../img/messenger/btn_write_01.gif" alt="입력" /></a>');
document.write('			</div>');
document.write('			<!--// 댓글 입력 -->');
document.write('		</div>');
document.write('		<!--// End -->');
		
document.write('		<!-- Start : 배경다름 -->');
document.write('		<div class="msgBlock bgType2">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" style="display:none;" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl>');
document.write('				<dt><strong>홍길동</strong> / 14:21</dt>');
document.write('				<dd class="msg">내가쓴글임내가쓴글임내가쓴글임</dd>');
document.write('				<dd class="btn"><span><a href="#"><img src="../img/messenger/btn_write.png" alt="쓰기" /></a></span></dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
			
document.write('			<!-- 댓글 입력 -->');
document.write('			<div class="write" style="display:none;">');
document.write('				<input type="text" value="15자 이내로 작성해 주세요." title="댓글입력" /><a href="#"><img src="../img/messenger/btn_write_01.gif" alt="입력" /></a>');
document.write('			</div>');
document.write('			<!--// 댓글 입력 -->');
document.write('		</div>');
document.write('		<!--// End : 배경다름 -->');
		
document.write('		<!-- Start -->');
document.write('		<div class="msgBlock">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" style="display:none;" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl>');
document.write('				<dt><strong>홍길동</strong> / 14:21</dt>');
document.write('				<dd class="msg">댓글쓰기를 눌렀을 경우</dd>');
document.write('				<dd class="btn"><span><a href="#"><img src="../img/messenger/btn_close_02.png" alt="닫기" /></a></span></dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
			
document.write('			<!-- 댓글 입력 -->');
document.write('			<div class="write">');
document.write('				<input type="text" value="15자 이내로 작성해 주세요." title="댓글입력" /><a href="#"><img src="../img/messenger/btn_write_01.gif" alt="입력" /></a>');
document.write('			</div>');
document.write('			<!--// 댓글 입력 -->');
document.write('		</div>');
document.write('		<!--// End -->');
			
document.write('		<!-- Start : 댓글 -->');
document.write('		<div class="msgBlock Reply">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl>');
document.write('				<dt><strong>홍길동</strong> / 14:21</dt>');
document.write('				<dd class="msg">댓글이 본인글이면 삭제버튼이</dd>');
document.write('				<dd class="btn"><span><a href="#"><img src="../img/messenger/btn_del.png" alt="삭제" /></a></span></dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
document.write('		</div>');
document.write('		<!--// End : 댓글 -->');
		
document.write('		<!-- Start : 댓글 -->');
document.write('		<div class="msgBlock Reply">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" style="display:none;" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl>');
document.write('				<dt><strong>홍길동</strong> / 14:21</dt>');
document.write('				<dd class="msg">댓글이 본인 글이 아니면..</dd>');
document.write('				<dd class="reply">&nbsp;</dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
document.write('		</div>');
document.write('		<!--// End : 댓글 -->');
		
document.write('		<!-- Start : 댓글 -->');
document.write('		<div class="msgBlock Reply">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl class="Admin">');
document.write('				<dt><strong>운영자</strong> / 14:21</dt>');
document.write('				<dd class="msg">운영자 본인이면 삭제버튼이..</dd>');
document.write('				<dd class="btn"><span><a href="#"><img src="../img/messenger/btn_del.png" alt="삭제" /></a></span></dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
document.write('		</div>');
document.write('		<!--// End : 댓글 -->');
		
document.write('		<!-- Start : 댓글 -->');
document.write('		<div class="msgBlock Reply">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" style="display:none;" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl class="Admin">');
document.write('				<dt><strong>운영자</strong> / 14:21</dt>');
document.write('				<dd class="msg">남들이 볼때 운영자</dd>');
document.write('				<dd class="reply">&nbsp;</dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
document.write('		</div>');
document.write('		<!--// End : 댓글 -->');
		
document.write('		<!-- Start : 배경다름 -->');
document.write('		<div class="msgBlock bgType2">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" style="display:none;" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl class="Admin"><!-- 관리자일 경우 -->');
document.write('				<dt><strong>운영자</strong> / 14:21</dt>');
document.write('				<dd class="msg">운영자가 쓴글도 댓글쓰기는 나와야지</dd>');
document.write('				<dd class="btn"><span><a href="#"><img src="../img/messenger/btn_write.png" alt="쓰기" /></a></span></dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
			
document.write('			<!-- 댓글 입력 -->');
document.write('			<div class="write" style="display:none;">');
document.write('				<input type="text" value="15자 이내로 작성해 주세요." title="댓글입력" /><a href="#"><img src="../img/messenger/btn_write_01.gif" alt="입력" /></a>');
document.write('			</div>');
document.write('			<!--// 댓글 입력 -->');
document.write('		</div>');
			
document.write('		<!-- Start : 댓글 -->');
document.write('		<div class="msgBlock bgType2 Reply">');
document.write('			<div class="pic">');
document.write('				<img src="../img/messenger/temp_01.jpg" alt="" class="pic" /><!-- 사진 SIZE : 34 x 34 -->');
document.write('				<img src="../img/messenger/bg_my.gif" alt="내가 쓴글 표시" class="myTalk" style="display:none;" /><!-- 내가 쓴 글일 경우에만 나타남 -->');
document.write('			</div>');
document.write('			<dl>');
document.write('				<dt><strong>홍길동</strong> / 14:21</dt>');
document.write('				<dd class="msg">댓글이 본인 글이 아니면..</dd>');
document.write('				<dd class="reply">&nbsp;</dd>');
document.write('			</dl>');
document.write('			<div class="ClearBlock"><!-- Clear Block --></div>');
document.write('		</div>');
document.write('		<!--// End : 댓글 -->');
document.write('		<!--// End : 배경다름 -->');
document.write('	</div>');
document.write('	<!--// content End -->');
	
document.write('	<!-- Footer Start -->');
document.write('	<div class="Bottom">');
document.write('		<span><a href="#"><img src="../img/messenger/btn_reload.gif" alt="새로고침" /></a></span>');
document.write('		<span>');
document.write('			<input type="text" title="검색" value="15자 이내로 작성해 주세요." />');
document.write('			<a href="#"><img src="../img/messenger/btn_send.gif" alt="보내기" /></a>');
document.write('		</span>');
document.write('	</div>');
document.write('	<!--// Footer End -->');
document.write('</div>');
document.write('<!--// Messenger End -->');